#+title: Core Config
#+author: Pratik Abhyankar

* Completions
** Which Key
Make Emacs prompt the next possible key bindings after a short while. I rely on
this a lot. Like.. a lot!
#+begin_src elisp
  (use-package which-key
    :ensure t
    :config
    (setq which-key-add-column-padding 1
          which-key-sort-uppercase-first nil
          which-key-show-early-on-C-h t
          which-key-idle-delay 1.0
          which-key-idle-secondary-delay 0.05)
    (which-key-mode))
#+end_src

** Ivy, Counsel and Swiper
My de-facto generic completion for Emacs. I don't do ~helm~, ~ido~ or ~vertico~;
please don't ask why.
*** Ivy
~ivy~ will setup the completion mechanism and enhance buffer switching.
#+begin_src elisp
  (use-package ivy
    :config
    (ivy-mode t)
    (setq ivy-use-virtual-buffers t
          ivy-count-format "(%d/%d) "
          ivy-initial-inputs-alist nil
          enable-recursive-minibuffers t)
    :bind (("C-x b" . ivy-switch-buffer)
           ("C-x B" . ivy-switch-buffer-other-window)
           ("C-c C-r" . ivy-resume)))
#+end_src

*** Swiper
The search mechanism that Emacs makes so so powerful!
#+begin_src elisp
  (use-package swiper
    :bind (("C-s" . swiper-isearch)
           ("C-M-s" . isearch-forward-regexp)
           ("C-M-r" . isearch-backwards-regexp)))
#+end_src

*** Counsel
~counsel~ enhances many default Emacs commands.
#+begin_src elisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x C-f" . counsel-find-file)
           ("C-c '" . counsel-imenu)
           ("C-c s" . counsel-rg)
           :map counsel-find-file-map
           ("RET" . ivy-alt-done)))
#+end_src

** Company

* Buffers
Make ~ibuffer~ the default buffer manager. Also, I don't want to see the buffers
that start with '*' such as ~*scratch*~ or ~*Messages*~ in the list, so I hide them.
#+begin_src elisp
  (use-package ibuffer
    :bind ("C-x C-b" . ibuffer))
  (require 'ibuf-ext)
  (add-to-list 'ibuffer-never-show-predicates "^\\*")
#+end_src

* Editing
** Electric
Teach Emacs some code-editing etiquette. I.. shouldn't have said that. Please
don't frown upon me!
#+begin_src elisp
  (delete-selection-mode)
  (electric-pair-mode 1)
#+end_src

** Undo Tree
Well.. this does undo redo. I don't like that it creates hidden ~~undotree~~ files
for every buffer, but I don't know how to disable that yet.
#+begin_src elisp
  (use-package undo-tree
    :config
    (global-undo-tree-mode t))
#+end_src

** Ws-butler
~ws-butler~ helps trim all white spaces at the end of line. I didn't know this
existed until I saw it in [[https://github.com/mtbar131/emacs/blob/master/custom/setup-editing.el][Amit's]] config!
#+begin_src elisp
  (use-package ws-butler
    :config
    (ws-butler-global-mode t))
#+end_src
