#+title: Org Mode Config
#+author: Pratik Abhyankar

* Flags
I tweak a few ~Org~ mode flags here to best suite my needs.

First things first, since I use literate config for Emacs, I don't want Emacs
to keep asking me for confirmation to execute code blocks.
#+begin_src elisp
	(setq-default  org-confirm-babel-evaluate nil)
#+end_src

All my ~org~ files usually reside in the ~~/org~ directory.
#+begin_src elisp
  (setq org-directory "~/org")
#+end_src

Make ~Org~ look subtly better.
#+begin_src elisp
  (setq-default
   org-hide-leading-stars t                  ;; Hide leading stars
   org-hide-emphasis-markers t               ;; Hide the Org markup indicators
   org-startup-indented t                    ;; Auto indent the body under headlines
   org-cycle-separator-lines 1               ;; Leave a line between org items
   org-src-fontify-natively t)               ;; Enable source code highlighting

#+end_src

Workflow settings for TODO items.
#+begin_src elisp
  (setq-default
   org-log-into-drawer t                     ;; Use LOGBOOK drawer to take notes
   org-log-done t                            ;; Add 'closed' log when marked done
   org-special-ctrl-a/e t                    ;; C-{a,e} should behave differently on headings
   org-enforce-todo-dependencies t           ;; Enforce tasks should be completed in order
   org-enforce-todo-checkbox-dependencies t) ;; Enforce checklist items should be completed in order
#+end_src

~Org~ agenda settings.
#+begin_src elisp
  (setq-default
   org-agenda-max-entries 10                 ;; Show at max 10 entries from my agenda
   org-agenda-dim-blocked-tasks nil          ;; highlights blocked tasks
   org-agenda-skip-scheduled-if-done t       ;; No need to honor schedule if the task is already done
   org-agenda-block-separator)               ;; Add a line to separate agenda items in dinstint sections
#+end_src

* ToDo Keywords
My ~org-todo-keywords~ match the stages from SIM tasks that I use at Amazon -
'Assigned', 'Implementation', 'Review', 'Release' and 'Done'. I have also added
a few more keywords like 'Waiting', 'Blocked' or 'Delegated' to further
fine-grain task statuses.
#+begin_src elisp
  (setq org-todo-keywords
        '((sequence "ASSIGNED(a)"
                    "IMPLEMENTATION(i)"
                    "BLOCKED(b)"
                    "WAITING(w)"
                    "REVIEW(r)"
                    "RELEASE(e)"
                    "|"
                    "DELEGATED(l)"
                    "DONE(d)")))
#+end_src

Let's also configure the org-todo-keyword-faces to match the ~Solarized~ theme that I use.
#+begin_src elisp
  (setq org-todo-keyword-faces
        '(("ASSIGNED" . "#dc322f")
          ("IMPLEMENTATION" . "#b58900")
          ("BLOCKED" . "#cb4b16")
          ("WAITING" . "#cb4b16")
          ("REVIEW" . "#2aa198")
          ("RELEASE" . "#268bd2")
          ("DELEGATED" . "#859900")
          ("DONE" . "#859900")))
#+end_src

* Packages

* Keybindings
Setup custom keybindings specific to ~Org~ mode.
#+begin_src elisp
  (bind-key "C-c a" 'org-agenda)
  (bind-key "C-c c" 'org-capture)
  (bind-key "C-c i b" 'org-indent-block)     ;; Handy keybinding to indent my 'org-blocks' in config
#+end_src
